{
 "title": "Balance",
 "description": "Some live-stats for the Brave New World series",
 "tags": [ "factorio" ],
 "time": { "from": "now-4h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Science / minute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Red",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"automation-science-pack\"}[1m])*80",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"automation-science-pack\"}[1m])*80",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Green",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"logistic-science-pack\"}[1m])*80",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"logistic-science-pack\"}[1m])*80",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Blue",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"chemical-science-pack\"}[1m])*80",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"chemical-science-pack\"}[1m])*80",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Purple",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"production-science-pack\"}[1m])*80",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"production-science-pack\"}[1m])*80",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Yellow",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"utility-science-pack\"}[1m])*80",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"utility-science-pack\"}[1m])*80",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Space",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"space-science-pack\"}[5m])*80",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"space-science-pack\"}[5m])*80",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  { "title": "Circuits / minute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Green",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"electronic-circuit\"}[1m])*80",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"electronic-circuit\"}[1m])*80",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Red",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"advanced-circuit\"}[1m])*80",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"advanced-circuit\"}[1m])*80",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Blue",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"processing-unit\"}[1m])*80",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"processing-unit\"}[1m])*80",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  { "title": "Materials / minute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Iron",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"iron-plate\"}[1m])*80",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"iron-plate\"}[1m])*80",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Copper",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"copper-plate\"}[1m])*80",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"copper-plate\"}[1m])*80",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Plastic",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"plastic-bar\"}[1m])*80",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"plastic-bar\"}[1m])*80",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Steel",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"steel-plate\"}[1m])*80",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"steel-plate\"}[1m])*80",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  { "title": "Components / minute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Battery",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"battery\"}[1m])*80",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"battery\"}[1m])*80",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Flying Robot Frame",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"flying-robot-frame\"}[1m])*80",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"flying-robot-frame\"}[1m])*80",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Low Density Structure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"low-density-structure\"}[2m])*80",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"low-density-structure\"}[2m])*80",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Rocket Control Unit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"rocket-control-unit\"}[2m])*80",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"rocket-control-unit\"}[2m])*80",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Rocket Fuel",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"rocket-fuel\"}[2m])*80",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"rocket-fuel\"}[2m])*80",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  }
 ]
}