{
 "title": "Bots",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Avaliable Logistics Robots",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "factorio_logistics_bots{type=~\"available_logistic_robots\", network_idx=\"1\"}"
    }
   ]
  },
  {
   "title": "Robot Types",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "factorio_logistics_bots{type=\"all_construction_robots\", network_idx=\"1\"}",
     "legendFormat": "Construction Robots"
    },
    {
     "expr": "factorio_logistics_bots{type=\"all_logistic_robots\", network_idx=\"1\"}",
     "legendFormat": "Logistic Robots"
    }
   ]
  },
  {
   "title": "Avaliable Construction Robots",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "factorio_logistics_bots{type=~\"available_construction_robots\", network_idx=\"1\"}"
    }
   ]
  },
  { "title": "Charging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Bots charging",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "factorio_logistics_bots{type=\"charging_bots\", network_idx=\"1\"}"
    }
   ]
  },
  {
   "title": "Bots waiting for charge",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "factorio_logistics_bots{type=\"waiting_for_charge\", network_idx=\"1\"}"
    }
   ]
  }
 ]
}