{
 "title": "#Infos",
 "description": "Some live-stats for the Brave New World series",
 "tags": [ "factorio" ],
 "time": { "from": "now-4h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Base", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Game Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "factorio_tick/60" }
   ]
  },
  {
   "title": "Players Online",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "factorio_online_players" }
   ]
  },
  {
   "title": "Factorio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "factorio_mods{name=\"base\"}==1"
    }
   ]
  },
  {
   "title": "Mods",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "factorio_mods{name!=\"base\", name!=\"graftorio\", name!=\"stdlib\", name!~\"nilaus_.*\", name!~\"tvc_.*\"}==1"
    }
   ]
  },
  {
   "title": "Seed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "factorio_seed" }
   ]
  },
  { "title": "Research", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Research",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "factorio_research_queue{index=\"1\"}",
     "legendFormat": "{{name}}: {{level}}"
    }
   ]
  },
  {
   "title": "Research Queue",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "factorio_research_queue{index!=\"1\"}"
    }
   ]
  },
  { "title": "Rockets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Rockets launched",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "factorio_items_launched_total", "legendFormat": "Rockets launched", "target": "randomWalk('myName')" }
   ]
  },
  {
   "title": "Rockets / hour",
   "type": "stat",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(factorio_items_launched_total[5m])*80*60",
     "legendFormat": "Rockets / hour",
     "target": "randomWalk('myName')"
    }
   ]
  },
  { "title": "Kills / minute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Biters",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(factorio_kill_count_input{name=~\".*-spawner\"}[5m])*80)",
     "legendFormat": "Spawner"
    },
    {
     "expr": "sum(rate(factorio_kill_count_input{name=~\"small.*\"}[5m])*80)",
     "legendFormat": "Small"
    },
    {
     "expr": "sum(rate(factorio_kill_count_input{name=~\"medium.*\"}[5m])*80)",
     "legendFormat": "Medium"
    },
    {
     "expr": "sum(rate(factorio_kill_count_input{name=~\"big.*\"}[5m])*80)",
     "legendFormat": "Big"
    },
    {
     "expr": "sum(rate(factorio_kill_count_input{name=~\"behemoth.*\"}[5m])*80)",
     "legendFormat": "Behemoth"
    }
   ]
  },
  {
   "title": "Defences",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(factorio_kill_count_output{name=~\".*-robot\"}[5m])*80)",
     "legendFormat": "Robots"
    },
    {
     "expr": "sum(rate(factorio_kill_count_output{name=\"stone-wall\"}[5m])*80)",
     "legendFormat": "Walls"
    },
    {
     "expr": "sum(rate(factorio_kill_count_output{name=~\".*-turret\"}[5m])*80)",
     "legendFormat": "Turrets"
    },
    {
     "expr": "sum(rate(factorio_kill_count_output{name!~\".*-worm-.*\", name!~\".*biter.*\", name!~\".*spitter.*\", name!~\"tree-.*\", name!~\".*rock-.*\", name!~\"nilaus-.*\", name!~\".*-robot\", name!=\"stone-wall\", name!~\".*-turret\"}[1m])*80)",
     "legendFormat": "Base"
    }
   ]
  }
 ]
}